### ISSUE TITLE
Bug when working with orientations 5 and 7

### ISSUE THREAD

**Issue by truist** [audreyt/image-jpegtran-auto#2]
Orientations 5 and 7 aren't transformed correctly. They generate a warning like so:

`Odd number of elements in hash assignment at .../Image/JpegTran.pm line 21`

Looking at that code in `Image::JpegTran::jpegtran()`:

~~~
    my %args = (                                                                
        @_==1 && ref $_[0] ? %{$_[0]} : @_                                      
    );                                                                          
~~~

...it looks like it's expecting either a single argument that's an arrayref or hashref, or an (even-numbered) array of arguments. (This is after the `from` and `to` have been shifted off.)

Looking at the call to that function in `auto_rotate()`:

`jpegtran($from => ($tmp || $to), @$transform);`

...in cases 5 and 7 `$transform` will be `['transpose']` and `['transverse']`, respectively. Those are converted to standard arrays during the call to `jpegtran()`, but they will only have one element, triggering the warning from `jpegtran()` and the failure to handle the transformation.

You can get test images from https://github.com/recurser/exif-orientation-examples and you can see an example (as of this writing) of those images and this issue at https://gallery.rainskit.com/Test/exif-orientation-examples/.

**Comment by audreyt** [comment]
Thanks! Released as 0.04 on CPAN.
